ALTER TABLE [dbo].[group]
        ADD NickName nvarchar(8) NOT NULL
 CONSTRAINT G_NickCol --When Omitted a Default-Constraint Name is autogenerated.
    DEFAULT ('')--Optional Default-Constraint.
WITH VALUES;

ALTER TABLE users
        ADD NickName nvarchar(5) NOT NULL
 CONSTRAINT U_NickCol --When Omitted a Default-Constraint Name is autogenerated.
    DEFAULT ('')--Optional Default-Constraint.
WITH VALUES

ALTER TABLE schedule
        ADD NickName nvarchar(5) NOT NULL
 CONSTRAINT S_NickCol --When Omitted a Default-Constraint Name is autogenerated.
    DEFAULT ('')--Optional Default-Constraint.
WITH VALUES